version: "3.3"

services:

  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen-api

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.nginx
    environment:
      - WEB_DOCUMENT_ROOT=/www/api/public
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    volumes:
      - ./:/www
    depends_on:
      - database

volumes:
  db-volume:
