version: "3.3"

services:

  database:
    container_name: database
    build:
      dockerfile: ./docker/Dockerfile.database
    environment:
      - MYSQL_DATABASE=lumen-api
      - MYSQL_USER=deverso
      - MYSQL_PASSWORD=deverso
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  api:
    container_name: api
    image: webdevops/php-nginx:alpine-php7
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    volumes:
      - ./app:/tmp/web
    depends_on:
      - database

volumes:
  db-volume:
