version: "3.3"

services:

  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen-api
    volumes:
      - db-volume:/var/lib/mysql

  api:
    container_name: api
    image: webdevops/php-nginx:alpine-php7
    environment:
      - WEB_DOCUMENT_ROOT=/www/api/public
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    volumes:
      - ./:/www
    depends_on:
      - database

  # pma:
  #   container_name: pma
  #   image: phpmyadmin/phpmyadmin
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=root
  #     - PMA_HOST=database
  #     - PMA_PORTS=3306      
  #   ports:
  #     - "80:80"
  #   depends_on: 
  #     - database

volumes:
  db-volume:
